"use client";

import * as React from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Copy } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { SettingsSection } from "@/modules/settings/components/SettingsSection";
import {
  useSecurityMutation,
  useTfaSetup,
} from "@/modules/settings/controllers/settingsController";
import {
  tfaVerifySchema,
  type TfaVerifyValues,
} from "@/modules/settings/lib/validators";

function Step({
  index,
  title,
  children,
}: {
  index: number;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="space-y-2">
      <p className="text-sm font-medium text-foreground">
        Step {index} — {title}
      </p>
      <div className="text-sm text-muted-foreground">{children}</div>
    </div>
  );
}

export function TwoFactorForm() {
  const { data, isLoading } = useTfaSetup();
  const mutation = useSecurityMutation("Two-factor authentication enabled.");
  const form = useForm<TfaVerifyValues>({
    resolver: zodResolver(tfaVerifySchema),
    defaultValues: { code: "" },
    mode: "onChange",
  });

  const onSubmit = () => {
    mutation.mutate(undefined, { onSuccess: () => form.reset({ code: "" }) });
  };

  const copyKey = () => {
    if (!data) return;
    navigator.clipboard?.writeText(data.secretKey).then(
      () => toast.success("Secret key copied."),
      () => toast.error("Could not copy the key."),
    );
  };

  return (
    <SettingsSection
      title="Two Factor Authentication"
      description="Increase your account's security by setting up two-factor authentication."
    >
      <Step index={1} title="Download an authenticator app">
        If you don&apos;t have one installed, we recommend Google Authenticator
        or Microsoft Authenticator.
      </Step>

      <Step index={2} title="Scan the barcode / QR code">
        Use your authenticator app to scan the code. Alternatively, copy the key
        below and paste it into the app.
        <div className="mt-2 flex flex-wrap items-center gap-2">
          {isLoading ? (
            <Skeleton className="h-9 w-72" />
          ) : (
            <>
              <code className="rounded-md border border-border bg-muted px-3 py-1.5 text-xs tracking-wide text-foreground">
                {data?.secretKey}
              </code>
              <Button variant="outline" size="sm" onClick={copyKey}>
                <Copy className="size-4" />
                Copy key
              </Button>
              <button
                type="button"
                onClick={() => toast.message("QR code — coming soon.")}
                className="text-xs font-medium text-info hover:underline"
              >
                View Barcode/QR Code
              </button>
            </>
          )}
        </div>
      </Step>

      <Step index={3} title="Enter your 6-digit code">
        Enter the 6-digit code generated by your authenticator app.
        <div className="mt-2 flex flex-wrap items-start gap-2">
          <div className="space-y-1">
            <Input
              inputMode="numeric"
              maxLength={6}
              placeholder="000000"
              className="w-40 tracking-[0.4em]"
              {...form.register("code")}
            />
            {form.formState.errors.code ? (
              <p className="text-xs text-destructive">
                {form.formState.errors.code.message}
              </p>
            ) : null}
          </div>
          <Button
            isLoading={mutation.isPending}
            disabled={!form.formState.isValid}
            onClick={form.handleSubmit(onSubmit)}
          >
            Submit
          </Button>
        </div>
      </Step>
    </SettingsSection>
  );
}
